source "https://rubygems.org"

group :jekyll_plugins do
  gem "jekyll-bookshop", "2.2.2"
  gem "cloudcannon-jekyll-bookshop", "2.2.2"
  gem 'jekyll-watch', :git => "https://github.com/CloudCannon/jekyll-watch"
  gem 'jekyll-tagging'
  gem "jekyll-sitemap"
  gem "jekyll-pagebreak", "~> 0.3"
  gem 'jekyll-redirect-from', :git => "https://github.com/jekyll/jekyll-redirect-from"
  gem 'jekyll-seo-tag'
end
