title: Android Talks
description: Podcast, w którym opowiadam o tworzeniu aplikacji mobilnych, kładąc szczególny nacisk na architekturę, bezpieczeństwo, testy oraz biblioteki i narzędzia, z których warto korzystać.
social_media_share_image: /images/01.jpg
disqus-identifier:
google-analytics: